#define IDD_MAIN                102
#define IDI_MAIN                128
#define IDC_FILE                1001
#define IDC_FOLDER              1002
#define IDC_SPLIT_SIZE          1003
#define IDC_FILE_BROWSE         1005
#define IDC_FOLDER_BROWSE       1006
#define IDC_SPLIT_TYPE          1009
#define IDC_SPLIT_RADIO         1011
#define IDC_JOIN_RADIO          1012
#define IDC_DELETE_SOURCE       1013
#define IDC_DO_IT               1014
#define IDC_ABOUT               1016
#define IDC_CLOSE               1015
#define IDC_PROGRESS            1017
#define IDC_STATIC              (-1)
